using System;
using System.Collections.Generic;

namespace Kaizen.CMS
{
    public partial class CM00151
    {
        public int TableID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DuplicateRow { get; set; }
        public string CaseRef { get; set; }
        public string EmployerName { get; set; }
        public Nullable<int> PastDueCount { get; set; }
        public Nullable<int> OverDueCount { get; set; }
        public string CIFNumber { get; set; }
        public string CIFName { get; set; }
        public string NationalityName { get; set; }
        public string NationaltyIDCIF { get; set; }
        public string CPRCRNo { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string PriorityName { get; set; }
        public Nullable<double> NPA { get; set; }
        public Nullable<double> TaskComplated { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
        public Nullable<bool> IsJoint { get; set; }
        public Nullable<int> CYCLEDAY { get; set; }
        public Nullable<int> BucketPrev { get; set; }
        public string BucketPrevName { get; set; }
        public Nullable<int> BucketID { get; set; }
        public string BucketName { get; set; }
        public Nullable<int> Lookup01 { get; set; }
        public string Lookup01Name { get; set; }
        public Nullable<int> Lookup02 { get; set; }
        public string Lookup02Name { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string TxtField01 { get; set; }
        public string TxtField02 { get; set; }
        public string TxtField03 { get; set; }
        public string TxtField04 { get; set; }
        public string TxtField05 { get; set; }
        public string TxtField06 { get; set; }
        public string TxtField07 { get; set; }
        public Nullable<bool> CheckBoxField02 { get; set; }
        public Nullable<bool> CheckBoxField01 { get; set; }
        public Nullable<double> AMT01 { get; set; }
        public Nullable<double> AMT02 { get; set; }
        public Nullable<double> AMT03 { get; set; }
        public Nullable<double> AMT04 { get; set; }
        public Nullable<double> AMT05 { get; set; }
        public Nullable<double> AMT06 { get; set; }
        public Nullable<double> AMT07 { get; set; }
        public Nullable<double> AMT08 { get; set; }
        public Nullable<double> AMT09 { get; set; }
        public Nullable<double> AMT10 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date02 { get; set; }
        public Nullable<System.DateTime> Date03 { get; set; }
        public Nullable<System.DateTime> Date04 { get; set; }
        public Nullable<double> PrincipleAmount { get; set; }
        public Nullable<double> MaturityAmount { get; set; }
        public Nullable<double> OutstandingAMT { get; set; }
        public Nullable<double> OutStandingToday { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
        public double ClaimAmount { get; set; }
        public Nullable<double> FinanceCharge { get; set; }
        public Nullable<double> WriteOffAMT { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public Nullable<double> LastPaymentAMTUpload { get; set; }
        public Nullable<double> TotalLifeCollactedAMT { get; set; }
        public string CaseAccountNo { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> OverDueDays { get; set; }
        public Nullable<System.DateTime> FirstDisburementDate { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> OverDueDate { get; set; }
        public Nullable<System.DateTime> LastPaymentDateUplod { get; set; }
        public Nullable<System.DateTime> FirstLifeOverDueDate { get; set; }
        public string Remarks { get; set; }
        public string AgentID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string AssignHistoryID { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<double> LastCallactedAMT { get; set; }
        public Nullable<double> TotalCallactedAMT { get; set; }
        public Nullable<double> CommissionRate { get; set; }
        public string LastPaymentBy { get; set; }
        public Nullable<double> MonthlySalary { get; set; }
        public string AddressCode { get; set; }
        public string CaseAddess { get; set; }
        public string Phone01 { get; set; }
        public string Phone02 { get; set; }
        public string Phone03 { get; set; }
        public string Phone04 { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string MobileNo3 { get; set; }
        public string MobileNo4 { get; set; }
        public string POBox { get; set; }
        public string Other01 { get; set; }
        public string Other02 { get; set; }
        public string Other03 { get; set; }
        public string Other04 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Email01 { get; set; }
        public string Email02 { get; set; }
        public string Email03 { get; set; }
        public string Email04 { get; set; }
        public string FlatNo { get; set; }
        public string BuildingNo { get; set; }
        public string RoadName { get; set; }
        public string RoadNo { get; set; }
        public string BlockNo { get; set; }
        public string BlockName { get; set; }
    }
}
