using System;
using System.Collections.Generic;

namespace Kaizen.CMS
{
    public partial class CM00203View01
    {
        public string UserName { get; set; }
        public string CaseRef { get; set; }
        public string TRXTypeID { get; set; }
        public string TrxTypeName { get; set; }
        public string ContractID { get; set; }
        public string ContractName { get; set; }
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string BatchID { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<byte> DecimalDigit { get; set; }
        public Nullable<bool> IsMultiply { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public string CIFNumber { get; set; }
        public string CPRCRNo { get; set; }
        public string CIFName { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string PriorityName { get; set; }
        public Nullable<double> NPA { get; set; }
        public Nullable<double> TaskComplated { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public Nullable<bool> IsJoint { get; set; }
        public Nullable<bool> IsHasHistory { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int CaseStatusID { get; set; }
        public Nullable<int> CaseStatusChild { get; set; }
        public string CaseStatusname { get; set; }
        public string CaseStatusChildName { get; set; }
        public string CaseStatusComment { get; set; }
        public Nullable<System.DateTime> ReminderDateTime { get; set; }
        public Nullable<double> PTPAMT { get; set; }
        public Nullable<int> PTPCount { get; set; }
        public Nullable<int> PTPBroken { get; set; }
        public Nullable<int> PTPkept { get; set; }
        public Nullable<int> LastCaseStatusID { get; set; }
        public Nullable<int> LastCaseStatusChildID { get; set; }
        public string LastCaseStatusname { get; set; }
        public string LastCaseStatusChildName { get; set; }
        public string LastCaseStatusComment { get; set; }
        public Nullable<int> MidCaseStatusID { get; set; }
        public Nullable<int> MidCaseStatusChild { get; set; }
        public string MidCaseStatusname { get; set; }
        public string MidCaseStatusChildName { get; set; }
        public string MidCaseStatusComment { get; set; }
        public Nullable<int> CYCLEDAY { get; set; }
        public Nullable<int> BucketPrev { get; set; }
        public string BucketPrevName { get; set; }
        public string BucketID { get; set; }
        public string BucketName { get; set; }
        public Nullable<int> Lookup01 { get; set; }
        public string Lookup01Name { get; set; }
        public Nullable<int> Lookup02 { get; set; }
        public string Lookup02Name { get; set; }
        public string TxtField01 { get; set; }
        public string TxtField02 { get; set; }
        public string TxtField03 { get; set; }
        public string TxtField04 { get; set; }
        public string TxtField05 { get; set; }
        public Nullable<bool> CheckBoxField02 { get; set; }
        public Nullable<bool> CheckBoxField01 { get; set; }
        public Nullable<double> AMT01 { get; set; }
        public Nullable<double> AMT02 { get; set; }
        public Nullable<double> AMT03 { get; set; }
        public Nullable<double> AMT04 { get; set; }
        public Nullable<double> AMT05 { get; set; }
        public Nullable<double> AMT06 { get; set; }
        public Nullable<double> AMT07 { get; set; }
        public Nullable<double> AMT08 { get; set; }
        public Nullable<System.DateTime> Date01 { get; set; }
        public Nullable<System.DateTime> Date02 { get; set; }
        public Nullable<System.DateTime> Date03 { get; set; }
        public Nullable<System.DateTime> Date04 { get; set; }
        public Nullable<double> PrincipleAmount { get; set; }
        public Nullable<double> MaturityAmount { get; set; }
        public Nullable<double> OutstandingAMT { get; set; }
        public Nullable<double> OutStandingToday { get; set; }
        public Nullable<double> InstallmentAmount { get; set; }
        public double ClaimAmount { get; set; }
        public Nullable<double> FinanceCharge { get; set; }
        public Nullable<double> WriteOffAMT { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public Nullable<double> LastPaymentAMTUpload { get; set; }
        public Nullable<double> TotalLifeCollactedAMT { get; set; }
        public string CaseAccountNo { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> OverDueDays { get; set; }
        public Nullable<System.DateTime> FirstDisburementDate { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> OverDueDate { get; set; }
        public Nullable<System.DateTime> LastPaymentDateUpload { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<System.DateTime> FirstLifeOverDueDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AgentID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<double> LastCallactedAMT { get; set; }
        public Nullable<double> TotalCallactedAMT { get; set; }
        public string LastPaymentBy { get; set; }
        public string AddressCode { get; set; }
        public string AddressName { get; set; }
        public string CaseAddess { get; set; }
    }
}
