USE [master]

/****** Object:  Database [Greenology]    Script Date: 4/26/2016 5:03:22 PM ******/
CREATE DATABASE [Greenology]

ALTER DATABASE [Greenology] SET COMPATIBILITY_LEVEL = 100


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Greenology].[dbo].[sp_fulltext_database] @action = 'enable'
end


ALTER DATABASE [Greenology] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [Greenology] SET ANSI_NULLS OFF 


ALTER DATABASE [Greenology] SET ANSI_PADDING OFF 


ALTER DATABASE [Greenology] SET ANSI_WARNINGS OFF 


ALTER DATABASE [Greenology] SET ARITHABORT OFF 


ALTER DATABASE [Greenology] SET AUTO_CLOSE OFF 


ALTER DATABASE [Greenology] SET AUTO_SHRINK OFF 


ALTER DATABASE [Greenology] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [Greenology] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [Greenology] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [Greenology] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [Greenology] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [Greenology] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [Greenology] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [Greenology] SET  DISABLE_BROKER 


ALTER DATABASE [Greenology] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [Greenology] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [Greenology] SET TRUSTWORTHY OFF 


ALTER DATABASE [Greenology] SET ALLOW_SNAPSHOT_ISOLATION ON 


ALTER DATABASE [Greenology] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [Greenology] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [Greenology] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [Greenology] SET RECOVERY FULL 


ALTER DATABASE [Greenology] SET  MULTI_USER 


ALTER DATABASE [Greenology] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [Greenology] SET DB_CHAINING OFF 


ALTER DATABASE [Greenology] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [Greenology] SET TARGET_RECOVERY_TIME = 0 SECONDS 


ALTER DATABASE [Greenology] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [Greenology] SET  READ_WRITE 



